
name: Scheduled test

on:
  schedule:
    - cron:  '55 5,10,17 * * *'

jobs:
  test:
    environment: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Test in Firefox Desktop
        env:
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          npx playwright install firefox --with-deps
          npm install -D @playwright/test
          npm test
