name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:

    environment: CI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Firefox Desktop
        env:
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
      - run: |
          npx playwright install firefox --with-deps
          npm install -D @playwright/test
          npm test
